name: CNOOC 公告检查（requests 版）

on:
  schedule:
    # 每天 00:00 和 12:00 各跑一次
    - cron: '0 */12 * * *'
  workflow_dispatch:  # 手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          KEYWORD: ${{ secrets.KEYWORD }}
        run: python3 check.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: cnooc_result
          path: output/
          retention-days: 7
